/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000504' at '18/9/16 11:37 PM' with Gradle 2.14.1
 *
 * @author IT000504, @date 18/9/16 11:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
