/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '25/12/16 8:42 PM' with Gradle 2.14.1
 *
 * @author IT000531, @date 25/12/16 8:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
